"""Build a double-clickable Prompter.app that starts the sidecar and opens the page.

    uv run --with pillow python launcher/make_app.py            # -> ~/Desktop/Prompter.app
    uv run --with pillow python launcher/make_app.py /Applications/Prompter.app

The app is a plain bundle around a shell script: if nothing answers on the port it
starts `uv run uvicorn ...` detached (log in ~/Library/Logs/prompter.log), waits for
/api/status, then opens Chrome (or the default browser). Clicking it again while the
server runs just opens the page. Quit from the page's "Quit prompter" button, or let
the server's idle exit stop it after the page has been closed for a while.
"""

from __future__ import annotations

import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PORT = int(os.environ.get("PROMPTER_PORT", "8765"))
UV = shutil.which("uv") or "/opt/homebrew/bin/uv"

LAUNCHER = f"""#!/bin/bash
# Prompter launcher. Generated by launcher/make_app.py; edit that, not this.
REPO="{REPO}"
PORT={PORT}
URL="http://localhost:$PORT"
LOG="$HOME/Library/Logs/prompter.log"
UV="{UV}"
[ -x "$UV" ] || UV="$(command -v uv 2>/dev/null)"
[ -x "$UV" ] || UV="$HOME/.local/bin/uv"

alive() {{ curl -s --max-time 1 "$URL/api/status" >/dev/null 2>&1; }}

if ! alive; then
  if [ ! -x "$UV" ]; then
    osascript -e 'display alert "Prompter could not start" message "uv was not found. Install it with: brew install uv" as critical'
    exit 1
  fi
  mkdir -p "$(dirname "$LOG")"
  echo "=== $(date) launching prompter from {REPO}" >> "$LOG"
  cd "$REPO" || exit 1
  nohup "$UV" run uvicorn server.main:app --host 127.0.0.1 --port "$PORT" >> "$LOG" 2>&1 &
  disown
  for i in $(seq 1 120); do
    alive && break
    sleep 0.5
  done
  if ! alive; then
    osascript -e 'display alert "Prompter could not start" message "The server did not answer within a minute. See ~/Library/Logs/prompter.log" as critical'
    exit 1
  fi
fi

if [ -d "/Applications/Google Chrome.app" ]; then
  open -a "Google Chrome" "$URL"
else
  open "$URL"
fi
"""


def make_icon(resources: Path) -> str | None:
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        print("pillow not available, skipping icon (run with: uv run --with pillow ...)")
        return None
    size = 1024
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    m = 64
    d.rounded_rectangle([m, m, size - m, size - m], radius=200, fill=(18, 18, 18, 255))
    # three lines of "script", the middle one lit like the current line
    grey, lit, accent = (120, 120, 120, 255), (242, 242, 242, 255), (255, 213, 74, 255)
    rows = [(300, 560, grey), (440, 700, lit), (580, 500, grey), (720, 640, grey)]
    for y, w, c in rows:
        d.rounded_rectangle([230, y, 230 + w, y + 64], radius=32, fill=c)
    # eye line with a marker on the left
    d.rectangle([150, 400, size - 150, 408], fill=accent)
    d.polygon([(118, 364), (118, 444), (190, 404)], fill=accent)
    iconset = resources / "AppIcon.iconset"
    iconset.mkdir(parents=True, exist_ok=True)
    for px in (16, 32, 128, 256, 512):
        img.resize((px, px), Image.LANCZOS).save(iconset / f"icon_{px}x{px}.png")
        img.resize((px * 2, px * 2), Image.LANCZOS).save(iconset / f"icon_{px}x{px}@2x.png")
    icns = resources / "AppIcon.icns"
    try:
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(icns)], check=True)
    except Exception as e:  # noqa: BLE001
        print("iconutil failed, no icon:", e)
        shutil.rmtree(iconset, ignore_errors=True)
        return None
    shutil.rmtree(iconset, ignore_errors=True)
    return "AppIcon"


def build(target: Path):
    if target.exists():
        shutil.rmtree(target)
    contents = target / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)
    exe = macos / "Prompter"
    exe.write_text(LAUNCHER)
    exe.chmod(exe.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    icon = make_icon(resources)
    plist = {
        "CFBundleName": "Prompter",
        "CFBundleDisplayName": "Prompter",
        "CFBundleIdentifier": "dk.mrs.prompter.launcher",
        "CFBundleVersion": "1",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": "Prompter",
        "LSMinimumSystemVersion": "13.0",
        "LSUIElement": True,  # no Dock icon; the script exits once the page is open
    }
    if icon:
        plist["CFBundleIconFile"] = icon
    with open(contents / "Info.plist", "wb") as f:
        plistlib.dump(plist, f)
    if shutil.which("codesign"):
        subprocess.run(["codesign", "--force", "--sign", "-", str(target)], check=False, capture_output=True)
    print(f"built {target}")
    print(f"  server: {UV} run uvicorn server.main:app --port {PORT}  (in {REPO})")
    print("  log:    ~/Library/Logs/prompter.log")


if __name__ == "__main__":
    out = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else Path("~/Desktop/Prompter.app").expanduser()
    build(out)
